### ISSUE TITLE
[Feature Request]: Heading 3 support for Table of Contents

### ISSUE THREAD

**Issue by PrattiDev** [playfulprogramming/playfulprogramming#1134]
### Description

We currently do not support a third level of heading in the ToC component. This was out of scope during the initial design, but for more longform articles - particularly in series - it could be useful if there are a lot of concepts to over.

A demo exists in Figma, albeit it has not been spec'd yet, pending the review of this GitHub issue.

### Describe the solution you'd like

The current Figma design is as follows. Let me know what you think.

![chrome_WeiwkhRnA8](https://github.com/user-attachments/assets/46dadf39-b276-4e1b-b2ce-a57a9f7d1d8f)

**Comment by crutchcorn** [comment]
I actually don't like the third headings. It makes longer content like mine much more challenging to visually navigate
