### ISSUE TITLE
[Website Bug]: Broken Link

### ISSUE THREAD

**Issue by geoffturk** [playfulprogramming/playfulprogramming#1173]
### Description

https://github.com/playfulprogramming/playfulprogramming/blob/84861ecc29e9970e78aca59e6c6cf35e8bac50bb/content/crutchcorn/collections/framework-field-guide-fundamentals/posts/ffg-fundamentals-preface/index.md?plain=1#L139

It's a 404:
https://playfulprogramming.com/posts/css-fundamentals

Maybe you want:
https://playfulprogramming.com/posts/web-fundamentals-css

**Comment by crutchcorn** [comment]
Any chance you'd wanna make a PR for this? :)

**Comment by geoffturk** [comment]
Sure, no problem. 👍  #1174

**Comment by crutchcorn** [comment]
Thank you @geoffturk!
