### ISSUE TITLE
ESLint 9 + ESLint Flat Config

### ISSUE THREAD

**Issue by crutchcorn** [playfulprogramming/playfulprogramming#1178]
Per ESLint 9, all configurations must now follow [a "Flat configuration" layout](https://eslint.org/docs/latest/use/configure/migration-guide)

This is also a blocker of upgrading TypeScript ESLint 7 -> 8

This would be an awesome community contribution

**Comment by The-CodeINN** [comment]
Hi @crutchcorn 

I opened a request for this [#1181](https://github.com/playfulprogramming/playfulprogramming/pull/1181)

**Comment by crutchcorn** [comment]
Closed by #1181
