### ISSUE TITLE
Fix Sass Deprecation Warnings

### ISSUE THREAD

**Issue by crutchcorn** [playfulprogramming/playfulprogramming#1179]
Sass has deprecated and plans to remove [`@import`](https://sass-lang.com/documentation/at-rules/import/), a few `&` nesting rules, and more.

First, follow the instructions in the `pnpm build` output to remove any deprecated plans. Most of these should come with an automated changelog provided in the deprecation warning, like so:

<img width="773" alt="image" src="https://github.com/user-attachments/assets/8e9d12dc-c435-4e7f-954f-51681226113d">

> https://sass-lang.com/documentation/breaking-changes/import/

Finally, let's migrate to the modern compiler using this Vite config: https://github.com/oceanbit/new-oceanbit-site/blob/main/astro.config.mjs#L4-L12

**Comment by Ibinola** [comment]
would love to jump on this ?

**Comment by crutchcorn** [comment]
@Ibinola that would be awesome! Feel free to take a stab at it, but also feel free to:

- Make a PR that's a WIP so we can see progress as you go
- [Join our Discord](https://discord.gg/FMcvc6T) so that we can help answer questions

**Comment by The-CodeINN** [comment]
@Ibinola Are you still working on this??

**Comment by The-CodeINN** [comment]
@crutchcorn I noticed the `build` takes long. I tried using a VM, GitHub codespace and even my PC. No success.

Getting stuck here: 

![image](https://github.com/user-attachments/assets/7a2f06c9-0a7c-4ce1-b653-0b3967c74dbe)

**Comment by The-CodeINN** [comment]
@crutchcorn 

I noticed an import statement `@import "src/tokens/index";` and `@import "./vars";` appearing in several SCSS files, particularly in the `src/components` folder. However, I cannot locate this file in the repository.

Also `src/views/search/components/filter-sidebar-props.scss`

When attempting to run the `sass-migrator` on these files, I'm encountering errors.

Could you help clarify where this tokens file should be located or how to properly handle these imports?

**Comment by crutchcorn** [comment]
`src/tokens/index` refers to the code from the root folder, ala:

https://github.com/playfulprogramming/playfulprogramming/blob/main/src/tokens/_index.scss

And the `vars` is actually an `_vars` import here: 

https://github.com/playfulprogramming/playfulprogramming/blob/22002fdb81489de9ad6ce5dcf74c80827b7d2e45/src/tokens/_vars.scss

Finally, `filter-sidebar-props.scss` should be here:

https://github.com/playfulprogramming/playfulprogramming/blob/main/src/views/search/components/filter-sidebar-props.scss

These aliases _should_ work fine, so it appears to be a bug in the migrator. However, you can change them to the full relative path, migrate, then change them back

**Comment by The-CodeINN** [comment]
Alright, thanks. Would do.

**Comment by The-CodeINN** [comment]
@crutchcorn 

I made some changes on this issue, but I figure that the changes cut across most of the `SCSS` files. Kindly this WIP if it is in the right direction.

**Comment by crutchcorn** [comment]
That WIP looks like it's on the right path!

**Comment by The-CodeINN** [comment]
This can be closed...
