### ISSUE TITLE
[Website Bug]: Article series navigation is broken

### ISSUE THREAD

**Issue by PrattiDev** [playfulprogramming/playfulprogramming#1226]
### Description

![image](https://github.com/user-attachments/assets/b80e5574-1353-4116-9dee-854a8af71687)

![image](https://github.com/user-attachments/assets/c1e8b9d2-d0e0-4dd5-8308-2ddfb32438f5)

Embed favicons are also broken

![image](https://github.com/user-attachments/assets/f3ead896-fe58-4502-9c50-0ccd90d8c8cf)

### Minimal Reproduction

Demo: https://playfulprogramming.com/posts/angular-templates-start-to-source

**Comment by crutchcorn** [comment]
Let's make a new issue for the embed favicons. The rest should be done now
